// Calibration probe: find the exact cv::resize(INTER_LINEAR) semantics for 8-bit
// images so app/src/inference/cv_resize.cpp can be bit-exact.
//
// Tries several plausible fixed-point formulations against OpenCV ground truth
// generated by tools/dump_resize_probe.py and prints the mismatch count of each.
// Dev-only tool.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace {

constexpr int kBits = 11;
constexpr int kScale = 1 << kBits;

struct Case {
    std::string name;
    int src_width = 0, src_height = 0, src_channels = 0;
    int dst_width = 0, dst_height = 0, dst_channels = 0;
    std::vector<std::uint8_t> source;
    std::vector<std::uint8_t> reference;
};

std::vector<std::uint8_t> ReadBytes(const std::string &path) {
    std::ifstream stream(path, std::ios::binary | std::ios::ate);
    if (!stream) {
        throw std::runtime_error("cannot open " + path);
    }
    const std::streamsize size = stream.tellg();
    stream.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> data(static_cast<std::size_t>(size));
    stream.read(reinterpret_cast<char *>(data.data()), size);
    return data;
}

short RoundShort(double value) { return static_cast<short>(std::nearbyint(value)); }

struct Axis {
    std::vector<int> offset;
    std::vector<short> w0;
    std::vector<short> w1;
};

Axis BuildAxis(int src_size, int dst_size, bool weight_on_fraction, double scale_override = 0.0) {
    const double scale = scale_override > 0.0
                             ? scale_override
                             : static_cast<double>(src_size) / static_cast<double>(dst_size);
    Axis axis;
    axis.offset.resize(dst_size);
    axis.w0.resize(dst_size);
    axis.w1.resize(dst_size);
    for (int d = 0; d < dst_size; ++d) {
        double fx = (d + 0.5) * scale - 0.5;
        int sx = static_cast<int>(std::floor(fx));
        fx -= sx;
        if (sx < 0) {
            sx = 0;
            fx = 0.0;
        }
        if (sx + 1 >= src_size) {
            sx = src_size - 2;
            fx = 0.0;
        }
        axis.offset[d] = sx;
        if (weight_on_fraction) {
            axis.w1[d] = RoundShort(fx * kScale);
            axis.w0[d] = static_cast<short>(kScale - axis.w1[d]);
        } else {
            axis.w0[d] = RoundShort((1.0 - fx) * kScale);
            axis.w1[d] = static_cast<short>(kScale - axis.w0[d]);
        }
    }
    return axis;
}

inline std::uint8_t CombineInt(std::uint8_t a, std::uint8_t b, short wa, short wb, int rounding) {
    const int value = (static_cast<int>(a) * wa + static_cast<int>(b) * wb + rounding) >> kBits;
    return static_cast<std::uint8_t>(std::clamp(value, 0, 255));
}

struct Variant {
    const char *name;
    bool weight_on_fraction;  // w1 = round(fx*scale) instead of w0 = round((1-fx)*scale)
    int rounding;             // rounding constant before the shift
    bool float_intermediate;  // keep the horizontal pass in float
    bool vertical_first;      // swap pass order
};

const Variant kVariants[] = {
    {"uchar rc=1024 w0", false, 1 << (kBits - 1), false, false},
    {"uchar rc=0    w0", false, 0, false, false},
    {"uchar rc=1024 w1", true, 1 << (kBits - 1), false, false},
    {"uchar rc=0    w1", true, 0, false, false},
    {"float rc=1024 w0", false, 1 << (kBits - 1), true, false},
    {"float rc=0    w0", false, 0, true, false},
    {"uchar rc=1024 w0 V-first", false, 1 << (kBits - 1), false, true},
    {"float rc=1024 w1", true, 1 << (kBits - 1), true, false},
};

std::vector<std::uint8_t> Resize(const Case &item, const Variant &variant) {
    const int channels = item.src_channels;
    const Axis x = BuildAxis(item.src_width, item.dst_width, variant.weight_on_fraction);
    const Axis y = BuildAxis(item.src_height, item.dst_height, variant.weight_on_fraction);
    if (item.src_width <= 1 || item.src_height <= 1) {
        return {};
    }
    const Axis &horizontal = variant.vertical_first ? y : x;
    const Axis &vertical = variant.vertical_first ? x : y;
    const int mid_width = variant.vertical_first ? item.src_width : item.dst_width;
    const int mid_height = variant.vertical_first ? item.dst_height : item.src_height;

    std::vector<std::uint8_t> result(static_cast<std::size_t>(item.dst_width) * item.dst_height * channels);

    // Pass 1
    std::vector<std::uint8_t> mid_u8(static_cast<std::size_t>(mid_width) * mid_height * channels);
    std::vector<float> mid_f(static_cast<std::size_t>(mid_width) * mid_height * channels);
    const int src_rows = variant.vertical_first ? item.src_width : item.src_height;
    const int src_cols = variant.vertical_first ? item.src_height : item.src_width;
    for (int row = 0; row < src_rows; ++row) {
        for (int d = 0; d < (variant.vertical_first ? mid_height : mid_width); ++d) {
            const int s = horizontal.offset[d];
            const short w0 = horizontal.w0[d];
            const short w1 = horizontal.w1[d];
            for (int c = 0; c < channels; ++c) {
                auto at = [&](int r, int cc) -> std::uint8_t {
                    const int rr = variant.vertical_first ? cc : r;
                    const int cc2 = variant.vertical_first ? r : cc;
                    return item.source[(static_cast<std::size_t>(rr) * item.src_width + cc2) * channels + c];
                };
                const std::uint8_t a = at(row, s);
                const std::uint8_t b = at(row, std::min(s + 1, src_cols - 1));
                const int mid_index = variant.vertical_first
                                          ? (d * mid_width + row) * channels + c
                                          : (row * mid_width + d) * channels + c;
                if (variant.float_intermediate) {
                    mid_f[mid_index] = static_cast<float>(a) * w0 + static_cast<float>(b) * w1;
                } else {
                    mid_u8[mid_index] = CombineInt(a, b, w0, w1, variant.rounding);
                }
            }
        }
    }

    // Pass 2
    for (int d = 0; d < (variant.vertical_first ? item.dst_width : item.dst_height); ++d) {
        const int s = vertical.offset[d];
        const short w0 = vertical.w0[d];
        const short w1 = vertical.w1[d];
        for (int col = 0; col < (variant.vertical_first ? item.dst_height : item.dst_width); ++col) {
            for (int c = 0; c < channels; ++c) {
                auto at = [&](int r) -> double {
                    const int mid_index = variant.vertical_first
                                              ? (col * mid_width + r) * channels + c
                                              : (r * mid_width + col) * channels + c;
                    return variant.float_intermediate ? static_cast<double>(mid_f[mid_index]) / kScale
                                                      : static_cast<double>(mid_u8[mid_index]);
                };
                const double a = at(s);
                const double b = at(std::min(s + 1, (variant.vertical_first ? mid_height : mid_width) - 1));
                const int out_index = variant.vertical_first
                                          ? (col * item.dst_width + d) * channels + c
                                          : (d * item.dst_width + col) * channels + c;
                if (variant.float_intermediate) {
                    const double value = (a * w0 + b * w1) / kScale;
                    result[out_index] = static_cast<std::uint8_t>(std::clamp(std::nearbyint(value), 0.0, 255.0));
                } else {
                    result[out_index] =
                        CombineInt(static_cast<std::uint8_t>(a), static_cast<std::uint8_t>(b), w0, w1,
                                   variant.rounding);
                }
            }
        }
    }
    return result;
}

}  // namespace

int main(int argc, char **argv) {
    if (argc < 2) {
        std::printf("usage: resize_probe <probe-dir>\n");
        return 2;
    }
    const std::string dir = argv[1];
    std::ifstream cases(dir + "/cases.txt");
    if (!cases) {
        std::printf("cannot read %s/cases.txt\n", dir.c_str());
        return 2;
    }
    std::vector<Case> items;
    std::string name;
    Case header;
    while (cases >> name >> header.src_width >> header.src_height >> header.src_channels >>
           header.dst_width >> header.dst_height >> header.dst_channels) {
        std::size_t src_bytes = 0, dst_bytes = 0;
        cases >> src_bytes >> dst_bytes;
        Case item = header;
        item.name = name;
        item.source = ReadBytes(dir + "/" + name + ".src.u8.bin");
        item.reference = ReadBytes(dir + "/" + name + ".dst.u8.bin");
        items.push_back(std::move(item));
    }
    std::printf("cases=%zu\n", items.size());

    for (const Variant &variant : kVariants) {
        long mismatched = 0;
        long total = 0;
        std::string worst;
        long worst_mismatch = -1;
        for (const Case &item : items) {
            const std::vector<std::uint8_t> mine = Resize(item, variant);
            if (mine.empty()) {
                continue;
            }
            long local = 0;
            for (std::size_t index = 0; index < mine.size(); ++index) {
                if (mine[index] != item.reference[index]) {
                    ++local;
                }
            }
            mismatched += local;
            total += static_cast<long>(mine.size());
            if (local > worst_mismatch) {
                worst_mismatch = local;
                worst = item.name;
            }
        }
        std::printf("%-26s mismatched=%8ld / %8ld (%.4f%%)  worst=%s\n", variant.name, mismatched,
                    total, total > 0 ? 100.0 * static_cast<double>(mismatched) / static_cast<double>(total) : 0.0,
                    worst.c_str());
    }
    return 0;
}
